# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "277647656486eb57390aca68d30e1eb4"
application_url = "https://star-rating.star-rating.workers.dev"
embedded = true
name = "star-rating"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"


[app_proxy]
url = "https://star-rating.star-rating.workers.dev/proxy"
prefix = "apps"
subpath = "star-rating"

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "/webhooks/compliance"

[auth]
redirect_urls = [ "https://star-rating.star-rating.workers.dev/api/auth" ]

[build]
automatically_update_urls_on_dev = true
